global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:9464']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'submission-service'
    static_configs:
      - targets: ['submission-service:9465']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'gamification-service'
    static_configs:
      - targets: ['gamification-service:9466']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'feedback-service'
    static_configs:
      - targets: ['feedback-service:9467']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:9468']
    scrape_interval: 10s
    metrics_path: /metrics